config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks'}

  root 'pages#index'
  get '/profile' => 'users#profile', :as => :profile

  namespace :admin do
    get '', to: 'dashboards#index', as: '/'
    get 'training', to: 'dashboards#training', as: 'training'
  end

  namespace :extension_api do
    resource :active_pages, only: [] do
      post 'tab_change'
      post 'new_page'
      post 'chrome_activated'
      post 'page_lost_focus'
    end

    resource :users do
      get :profile, on: :collection
    end

    resource :experiments, only: [] do
      post 'in_work'
      post 'not_in_work'
      get 'beer_count'
    end

  end

  namespace :api do
    resource :dashboards, only: [] do
      get :overview, on: :collection
      get :words_cloud, on: :collection
      get :spiral, on: :collection
    end
    resource :experiments, only: [] do
      get :application_list, on: :collection
      get :application_types, on: :collection
      post :app_categorization, on: :collection
    end
  end

  get '*path' => 'pages#index'

end

app/views/pages/_login_modal.html.erb
<div class="modal fade in" id="login">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h3 class="text-center"> Sign In</h3>
  </div>
  <div class="modal-body">
    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
            <%= f.email_field :email, :autofocus => true, placeholder: 'Email Address', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
          </div>
        </div>
        <% if devise_mapping.rememberable? -%>
            <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>
        <div class="modal-footer">
          <div><%= f.submit "Sign In", :class => 'btn btn-lg btn-block btn-primary' %></div>
          <p>

          <div><a href="#sign_up" data-toggle="modal" data-dismiss="modal">Sign up</a></div>
          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              <div>
                <%= link_to "Forgot your password?", new_password_path(resource_name) %><br/>
              </div>
          <% end -%>

          <%- if devise_mapping.omniauthable? %>
              <%- resource_class.omniauth_providers.each do |provider| %>
                  <div>
                    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
                  </div>
              <% end -%>
          <% end -%>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/pages/_sign_up_modal.html.erb
<div class="modal fade in" id="sign_up">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h3 class="text-center"> Sign Up</h3>
  </div>
  <div class="modal-body">
    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
            <%= f.email_field :email, :autofocus => true, placeholder: 'Email Address', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
            <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation', class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <div><%= f.submit "Sign Up", :class => 'btn btn-lg btn-block btn-primary' %></div>
          <p>

          <div><a href="#login" data-toggle="modal" data-dismiss="modal">Sign in</a></div>
          <%- if devise_mapping.omniauthable? %>
              <%- resource_class.omniauth_providers.each do |provider| %>
                  <div>
                    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
                  </div>
              <% end -%>
          <% end -%>

          </p>
        </div>
        </div>
    <% end %>
    </div>
</div>